# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed17cd502f8aef152dcd22ee09309453c68afb6809de286be5ef0a30fa03557ff5766e2624454a10e2947f863d7dbf491b3ac64a809f15ad2b95e2712c62f779

test:
  secret_key_base: 17a676d27eddb6f0197ba11e0018146fd0117f200a428a42310862d46ca9d51f4baa2a3f6aa8219b607da1418798c07cf2fe718e1b87bf8ffe46d6f0c912d11e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
